### PR TITLE
Add Broker.multi_manager

### PR DESCRIPTION
**Pull request by JacobCallahan**
This change introduces a way to carry out multiple kinds of checkouts at the same time when using Broker as a library.

from the docstring:
```
        Given a mapping of names to Broker argument dictionaries:
        create multiple Broker instances, check them out in parallel, yield, then checkin.
        Example:
            with Broker.multi_mode(
                rhel7={
                    "host_class": ContentHost,
                    "workflow": "deploy_base_rhel",
                    "deploy_rhel_version": "7",
                },
                rhel8={
                    "host_class": ContentHost,
                    "workflow": "deploy_base_rhel",
                    "deploy_rhel_version": "8",
                }
            ) as host_dict:
                pass
        All are checked out at the same time. The user is presented with the hosts in
        a dictionary by argument name e.g. host_dict["rhel7"] is a ContentHost object

```

### CODE REVIEW

**Comment by JacobCallahan** [comment]
New functional test passing
Screenshot from 2023-05-22 15-30-06

**Comment by JacobCallahan** [comment]
Now, there are some decisions that I'm not final on. Let me know what you all think about these?

1. When there is a single host, as a value per key, separate it from the list.
2. Perform all setup and teardown methods in a thread pool.

**Comment by JacobCallahan** [comment]
Ok, latest update also executes all host setup and teardown tasks in a thread pool

**Review by ogajduse — APPROVED** [review]
I like this feature. LGTM.
Great job, @JacobCallahan!

**Pull request merged**
