### PR TITLE
Add a tail_file context manager to the Host class

### PR DESCRIPTION
**Pull request by JacobCallahan**
This is a pretty common request and should be useful in a number of scenarios. Usage is pretty simple:
```python
    with my_host.session.tail_file("/var/log/messages") as res:
        # do something that creates new messages
    print(res.stdout)
```

### CODE REVIEW

**Comment by JacobCallahan** [comment]
I was debating whether this should be on the host object itself or on the host's session object. Let me know what you think. The alternative would look like this

```python
    with my_host.session.tail_file("/var/log/messages") as res:
        # do something that creates new messages
    print(res.stdout)
```

**Comment by JacobCallahan** [comment]
@rplevka the new version is in now. The downside I forgot about is that it needed to be duplicated for the ContainerSession, but that's not a big deal.

**Comment by JacobCallahan** [comment]
@Griffin-Sullivan great idea! Is that something you're wanting to do or would you prefer I handle that in this PR?

**Comment by Griffin-Sullivan** [comment]
I can do it in a separate PR.

**Pull request merged**
