### PR TITLE
Introducing multiprocessing for broker checkouts

### PR DESCRIPTION
**Pull request by JacobCallahan**
VMBroker now has the ability to multiprocess checkouts
The decorator is likely general to other VMBroker methods, but hasn't
been applied at this point.
Also, Broker is now v0.1.0

### CODE REVIEW

**Comment by JacobCallahan** [comment]
I'm debating about changing `--count` to some other name that won't potentially conflict with a legitimate checkout argument. maybe `broker-count`?
I'd like some options, please.

**Comment by mshriver** [comment]
Unit tests?

**Comment by akhil-jha** [comment]
How about `--enum` ? (enumerate)

**Comment by JacobCallahan** [comment]
@akhil-jha I'm afraid that would be confusing for people familiar with python's enumerate built-in.

**Pull request merged**
